var iotb = require('iotb');

var iotbapp=iotb({
  port:8081,
  systemadministrator:"iotadmin - <yourmail>",
  defaultadmin:{
    user: "iotadmin",                     // default admin username
    username: "IoT Broker Administrator", // default admin username long
    password: "<yourpwd>",                // default admin password
    email: "<yourmail>"                   // admin user mail address
  },
  dbfile:"./db/iot.db",        
  webpush:{
    // copy content from keys.txt generated by web-push
    publickey: "<public key>",
    privatekey: "<private key>",
    email: "<yourmail>"
  },
  limits:{
    zipfileupload_mb:5,
    websitetotalsize_mb:10
  }
});

var app=iotbapp.express;

iotbapp.run().then(()=>{
  console.log("IoT Broker listening on port "+iotbapp.config.port);
  let events = [
    {name: 'beforeExit', exitCode: 0 },
    {name: 'uncaughtExecption', exitCode: 1 },
    {name: 'SIGINT', exitCode: 130 },
    {name: 'SIGTERM', exitCode: 143 }
  ];

  events.forEach((e) => {
    process.on(e.name,  () => {
    iotbapp.stop()
      .then(() => { 
        console.log('connection cleaned');
        process.exit(e.exitCode);
      })
      .catch((err) => {
        console.error(err);
        process.exit(1);
      })    
    })
  });
}).catch((e)=>{
  console.log("Error loading IoT Broker");
  console.log(e);
});